---
# Broken bundler on travis CI - https://github.com/bundler/bundler/issues/2784
before_install:
  - gem update --system 3.0.0
  - gem --version
  - gem install bundler
language: ruby
rvm:
  - 2.3.0